sudo: enabled
dist: trusty
language: c
os:
- linux
compiler:
- gcc
before install:
- sudo apt-get -qq update
env:
  global:
  - OpenSSL::OPENSSL_VERSION=openssl-1.0.2
  - secure: ZHlZN5m28wi4lgPmSjrFpK8YI86qCEOI5fRnb5P35CemC3HKrxOkETlShichC9oOGEMUfxI/maaChqP3tmtCbimqjaMu/CIh/lxWCN3NuApO5vSDEWdoKeDaVQNSdyP0PKozwV2YHRLUot6dqXaH5gvN+BhE7/LsMBTDiIx0WmjULZZUBWorQJ47r/5pEMCYuKNOxh5q8pafqhQZOk6RjxyEuKisprH8xKuVRQG5qI8dSrn9erlnZYgbpzvdM76j/Uel/srHFUICdw/DedFduLYuQCDu5BbI+Ok12XoeaRTNiLSJZhUGZG/onkVa+QmTpzyknW6ewrXdv4jQytcNiGr33rlg9Wdu/gCjT3sXO6JMzWMB6spCmmF4RZjKO+VnxeHgG69Xoi28M9/Fni5EzvOaSoVJBwzDrYUJKC9gNqbXCqgu/Yg8a1T9HsyGDMkimXyS5slEsRa+EyIlhE0BoZZeBBtSVQr2rd+O8QEwjsv62+x9LfOS7S0AEbb26BCU7jRbMCkiiYqQS7/kdFJSTPDP0Gh/UNvG2gSR6fwI74yp54BDkATtD9cUFVG5Kh5AD/rNPQKhUkqyNIRaslgn8K2yB6sWFh3QPooOiAb9rVJnjehOChtqnWO8MoizeZSibAAsjsLyO13sKWXQj2HIwu4NzFsSciHg6Z7wrSelhnA=
  matrix:
  - CONFIGURE_OPTIONS='--enable-msspi' MSSPI='yes'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - libssl-dev
    - libwrap0-dev
install:
- if [ $MSSPI == yes ]; then wget https://$ACCOUNT@update.cryptopro.ru/support/stunnel/dist/csp40r3/linux-amd64_deb.tgz
  && tar -xvf linux-amd64_deb.tgz && sudo linux-amd64_deb/install.sh; fi
before_script:
- autoreconf -fvi && touch src/dhparam.c
- ln -s /usr/bin/g++-4.9 g++
- cd src/msspi/build_linux && make
- cd ../../..
- openssl version
- perl -v
script:
- "./configure $CONFIGURE_OPTIONS"
- make
- make test
- cd src
- sudo perl make_default_certs.pl
- sudo perl stunnel.pl local
- sudo killall stunnel
- cd ..
after_success:
deploy:
  provider: releases
  api_key:
    secure: RGEmJUGwhxQPdmkQA4bu6bYEU1XUDXamGAaoznYJVu0a+gIK2AfQI9Klifv2fhyVd3DXEzo2p9fVyb3Jtp2N4ynwRpzqa5EVARNK4OH9GO8YvAQ+gndHrAaa8l060shgy6tXNuxwPAdhh78UhZUEn6Cqz+ocBM6/RiriKMVdeLX3F5fO+0PuA69z9bc7pUkX326pLTNpl/ihiDCSoBAKMLHzOSjV+DKWUGO66sj8o4DVeZZ2zZC/f8HAdZZHHei12TNAQb/SNMUcGKFwhaFZXHOAUqE+AD7iCg1Qmsy1ilM7HJR5FN3d5Bb54y/V8V5YdYjezCB5HXUCcjfz4hSjjy+qeXgDTEVsTKelSNz3wkcmmXdXH6YugpnfNBegZnKbrEYMtif8TO0zowyaXgyoGdbv5EGfQCjNUVqt6tncampXgjGwUVfsMrsjDA0MG6gg0cbp3mMQFs50brbNJNJ75CSdWMbqjuwMozvIdrIhtbfgRk6Wfqia6wfQJHau6ktFUx9+gA2kVJdQzJwxGT44AtDW7aqzuVp2umEbw2I3IEQwC977aJiB22Q5WvjOM7Siz8DrgHZata9DGBLdV4IEaEFQWFY2xqLO35dCgl+GVGZcM/84X9NBXQm01LpgCFiwH9w9P4aQrYoW09TSDiAXRut+ws88lJgp3yQZGGIkIqY=
  skip_cleanup: true
  file: src/stunnel
  on:
    tags: true
